/*
 * Jumping Jack - a tribute to the 1983 ZX Spectrum classic.
 *
 * Platform-independent game core. Written in freestanding C (no libc),
 * so the very same file compiles to WebAssembly and to a native binary.
 *
 * The host calls jj_tick() 50 times per second (PAL Spectrum frame rate),
 * then blits jj_framebuffer() and queues jj_audio() samples.
 */
#ifndef JJ_GAME_H
#define JJ_GAME_H

/* Framebuffer: 256x192 Spectrum screen + 32/24 px border, RGBA bytes. */
#define JJ_W 320
#define JJ_H 240
#define JJ_FPS 50

/* Input bitmask passed to jj_tick(). */
#define JJ_KEY_LEFT 1u
#define JJ_KEY_RIGHT 2u
#define JJ_KEY_JUMP 4u
#define JJ_KEY_START 8u
#define JJ_KEY_PAUSE 16u

void jj_init(unsigned int seed);
void jj_set_sample_rate(int rate);
void jj_tick(unsigned int keys);

/* JJ_W*JJ_H pixels, each 4 bytes in R,G,B,A memory order. */
const unsigned int *jj_framebuffer(void);

/* Mono float samples (-1..1) generated by the last jj_tick(). */
const float *jj_audio(void);
int jj_audio_len(void);

unsigned int jj_hiscore(void);
void jj_set_hiscore(unsigned int score);

#endif
